<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array(
    'Б_K' => 'Белый король',
    'Ч_K' => 'Черный король',
    'Б_Ф' => 'Белый ферзь(королева)',
    'Ч_Ф' => 'Черный ферзь(королева)',
    'Б_Б' => 'Белая ладья(башня)',
    'Ч_Б' => 'Черная ладья(башня)',
    'Б_О' => 'Белый офицер',
    'Ч_О' => 'Черный офицер',
    'Б_Л' => 'Белый конь',
    'Ч_Л' => 'Черный конь',
    'Б_П' => 'Белая пешка',
    'Ч_П' => 'Черная пешка',   
    'short' => 'Каждый ход 3 мин',
    'chat' => 'Чат',
    'show chess' => 'Показать на примере шахмат',
    'competitor' => 'Соперник : ',
    'сhess_wiki' => 'Википедиа ШАХМАТЫ',    
    'long' => 'Неограниченные по времени',
    'figure_place_error' => 'Неправильно сделан ход',
    'Logs' => 'Перемещение фигур',
    'Create' => 'Сделать Ход',
    'Create Games' => 'Начать Игру',
    'List Games' => 'Список Игр',
    'Join Games' => 'Присоединиться к Игре',
    'My Games' => 'Мои активные Игры',
    'Joined Game' => 'Вы присоединились к игре № ',
    'Manage Games' => 'Редактировать Игры',
    'View Games' => 'Просмотр Игры',
    'Update Games' => 'Изменить тип игры',
    'Delete Games' => 'Удалить игру',
    'Save' => 'Сохранить',
    'Create Log' => 'Сделать ход',
    'List Log' => 'Список сделанных ходов',
    'long' => 'Неограниченная по времени',
    'name' => 'Зовут меня: <span class="required">*</span>',
    'email' => 'Почтовый адрес мой: <span class="required">*</span>',
    'subject' => 'Я здесь не просто так: <span class="required">*</span>',
    'Submit' => 'Желаю я отправить поскорей',
    'Submit_chat' => 'Сказать',
    'body' => 'История моя: <span class="required">*</span>',
    'Thank you for contacting us. We will respond to you as soon as possible.' => 'Спасибо за сообщение! Будем думать, будем думать что Вам ответить',
    'Verification Code' => 'А этот код от роботов преграда! <span class="required">*</span>',
    'Please enter the letters as they are shown in the image above.' => 'Еще раз буквы эти напиши? <span class="required">*</span>',
    'Letters are not case-sensitive.' => 'Размер пусть не волнует',
    'required' => '<p class="note">Значок <span class="required">*</span> не для красоты.</p>',
    'contact note' => 'Так что же привело тебя сюда?',
    'The property filterSelector should be defined.' => 'Свойство filterSelector должно быть определено.',
    'The property updateSelector should be defined.' => 'Свойство updateSelector должно быть определено.',
    'Are you sure you want to delete this item?' => 'Вы уверены, что хотите удалить эту игру?',
    'Delete' => 'Удалить',
    'Displaying {start}-{end} of 1 result.|Displaying {start}-{end} of {count} results.' => 'Элементы {start}—{end} из {count}.',
    'Either "name" or "value" must be specified for CDataColumn.' => 'Для CDataColumn необходимо указать "name" или "value".',
    'Home' => 'Главная',
    'About' => 'О проекте',
    'Contact' => 'Обратная связь',
    'Operations' => 'Возможности',
    'No results found.' => 'Нет результатов.',
    'Not set' => 'Не задан',
    'Please specify the "attributes" property.' => 'Задайте свойство "attributes".',
    'Please specify the "data" property.' => 'Задайте свойство "data".',
    'Sort by: ' => 'Сортировка: ',
    'The "dataProvider" property cannot be empty.' => 'Свойство "dataProvider" не может быть пустым.',
    'The attribute must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Атрибут должен быть указан в формате "Имя:Тип:Заголовок". "Тип" и "Заголовок" не обязательны.',
    'The button type "{type}" is not supported.' => 'Тип кнопки "{type}" не поддерживается.',
    'The column must be specified in the format of "Name:Type:Label", where "Type" and "Label" are optional.' => 'Столбец должен быть указан в формате "Name:Type:Label". "Тип" и "Заголовок" не обязательны.',
    'The property "itemView" cannot be empty.' => 'Свойство "itemView" не может быть пустым.',
    'Total 1 result.|Total {count} results.' => 'Всего {count} результат.|Всего {count} результата.|{count} результатов.|{count} результата.',
    'Update' => 'Редактировать',
    'View' => 'Просмотреть',
    '{class} must specify "model" and "{attribute}" or "{name}" property values.' => 'В классе {class} должны быть заданы значения свойств "model" и "{attribute}", либо значение "{name}".',
);
